# Generated by Django 4.1.2 on 2023-11-02 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notificationstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
