# Generated by Django 4.1.2 on 2023-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_tokensessionid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensessionid',
            name='last_used',
            field=models.DateTimeField(null=True),
        ),
    ]
