# Generated by Django 4.1.2 on 2023-11-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_tokensessionid_last_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastmessage',
            name='is_acknowleged_by_android',
        ),
        migrations.RemoveField(
            model_name='lastmessage',
            name='is_acknowleged_by_browser',
        ),
    ]
