# Generated by Django 4.1.2 on 2023-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_lastmessage_is_acknowleged_by_android_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_in_messages_box',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active_in_messages_list',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active_in_notifications_list',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
